### ISSUE TITLE
Missing PID file

### ISSUE THREAD

**Issue by astik** [elastic/ansible-beats#11]
Hi,

Using debian to work with ES, Kibana and beat. Using this ansible role to deploy metricbeat works fine, still, i'm missing the PID file creation, nothing is created in /var/run, no PID file. I'm no linux expert, so i may be missing something =/

Here is the command line that starts the process :

```
/usr/share/metricbeat/bin/metricbeat -c /etc/metricbeat/metricbeat.yml -path.home /usr/share/metricbeat -path.config /etc/metricbeat -path.data /var/lib/metricbeat -path.logs/var/log/metricbeat
```

The file that define service is /etc/init.d/metricbeat and contains : 

```
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Metricbeat is a lightweight shipper for metrics."
NAME="metricbeat"
DAEMON=/usr/share/${NAME}/bin/${NAME}
DAEMON_ARGS="-c /etc/${NAME}/${NAME}.yml -path.home /usr/share/${NAME} -path.config /etc/${NAME} -path.data /var/lib/${NAME} -path.logs /var/log/${NAME}"
TEST_ARGS="-e test config"
PIDFILE=/var/run/metricbeat.pid
WRAPPER="/usr/share/${NAME}/bin/${NAME}-god"
BEAT_USER="root"
WRAPPER_ARGS="-r / -n -p $PIDFILE"
SCRIPTNAME=/etc/init.d/metricbeat

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start \
                --pidfile $PIDFILE  \
		--exec $WRAPPER -- $WRAPPER_ARGS -- $DAEMON $DAEMON_ARGS \
		|| return 2
}
```

Here is my inventory :

```
beats:
  metricbeat:
    beat_conf:
      setup.dashboards.enabled: true
      metricbeat.modules:
        - module: system
          metricsets:
            - cpu
            - load
            - filesystem
            - fsstat
            - memory
            - network
            - process
          enabled: true
          period: 10s
          processes:
            - ".*"
```

and here is my role definition :

```
- hosts: servers
  roles:
    - role: ansible-beats
      beat: metricbeat
      beat_conf: "{{ beats.metricbeat.beat_conf }}"
```
