### ISSUE TITLE
 "use_repository: false" - Default URL Broken

### ISSUE THREAD

**Issue by humpalum** [elastic/ansible-beats#139]
**Beats product**:
metricbeat (probably others too?)

**Beats version**
7.11.2

**Role version**:  (If using master please specify github sha)
v7.11.2

**OS version** (`uname -a` if on a Unix-like system):
4.19.0-13-amd64 Debian (Host)
4.15.0-99-generic Ubuntu (Target)

**Description of the problem including expected versus actual behaviour**:
During the Download metricbeat from URL step, it fails. This happens, when using "use_repository: false" to download the packages without apt.

**Playbook**:
Please specify the full playbook used to reproduce this issue.
```

---
- hosts: all
  pre_tasks: 

    - name: includepasswords
      include_vars: passwords.yml

    - set_fact: ansible_sudo_pass={{vars[inventory_hostname + '_sudopass']}}
  roles:
    - role: elastic.beats
      become: yes
    
  vars:
    beats_version: 7.11.2
    beat: metricbeat
    beat_conf:
      metricbeat.modules:
      - module: system
        metricsets:
          - cpu             # CPU usage
          - load            # CPU load averages
          - memory          # Memory usage
          - network         # Network IO
          - process         # Per process metrics
          - process_summary # Process summary
          - uptime          # System Uptime
          #- socket_summary  # Socket summary
          #- core           # Per CPU core usage
          - diskio         # Disk IO
          - filesystem     # File system usage for each mountpoint
          - fsstat         # File system summary metrics
          #- raid           # Raid
          #- socket         # Sockets and connection info (linux only)
        enabled: true
        period: 30m
        processes: ['.*']
        # Configure the metric types that are included by these metricsets.

```
**Provide logs from Ansible**:
![image](https://user-images.githubusercontent.com/11175099/110800520-8bec3200-827c-11eb-9862-26c1a65b9d01.png)

**Comment by humpalum** [comment]
I feel somethings wrong with the task Set os_arch not setting the os_arch fact correctly as it seems to be set to "false" as the URL ends with "...False.deb"

```
- name: Set os_arch
  set_fact:
    os_arch: >-
      {{ ansible_architecture == 'x86_64' | ternary('amd64', 'i386') }}

```



```
- name: Debian - Download {{ beat }} from url
  get_url:
    url: >-
      {% if custom_package_url is defined %}{{ custom_package_url }}{%
        else %}{{ beats_package_url }}/{{ beat }}/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb{% endif %}
    dest: '/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb'
    validate_certs: false
  when: not use_repository | bool
```
