### ISSUE TITLE
And Elastic username and password for all beats

### ISSUE THREAD

**Issue by dNodal0** [elastic/ansible-beats#142]
Hello,

I would like to add Elasticsearch username and password like this in my playbook

output_conf:
   elasticsearch:
      hosts: http://localhost:9200
      password: ******
      username: *****

Regards.

**Comment by kd8drx** [comment]
Hello @dNodal0 - welcome to the community!

Take a look at the [docs for the `beat_conf` parameter](https://github.com/elastic/ansible-beats#basic-beats-configuration). Any items added under this key are directly added to the `${beat}.yml` config file (e.g. `filebeat.yml` for Filebeat)

For example, to provide the info above in `filebeat.yml`, you'd have something like:
```
beat_conf:
      filebeat:
        output_conf:
          elasticsearch:
            hosts: http://localhost:9200
            password: ******
            username: *****
```

For details on how your config files should look, [the main Beats documentation has _lots_ of examples](https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format.html).
