### ISSUE TITLE
`beat_conf.setup.ilm.policy_file` must be specified

### ISSUE THREAD

**Issue by ned-si** [elastic/ansible-beats#143]
**Beats product**: metricbeat/filebeat

**Beats version**: 7.11.1

**Role version**:  7.11.1, 7.11.2, 7.12.0

**OS version**: Linux xxxx 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:

Following [the doc](https://github.com/elastic/ansible-beats#focus-on-ilm), I wanted to add a custom ILM policy to my playbook. Up until now I was using the `beat_conf.setup.ilm.policy_name` field and it was working fine. 

When adding `default_ilm_policy` and `beat_conf.setup.ilm.policy_file`, Ansible returns this error:
```
fatal: [es-1]: FAILED! => {"changed": false, "msg": "beat_conf.setup.ilm.policy_file must be specified if default_ilm_policy is used"}
```
The issue is that it is indeed in the playbook. 

Expected behavior is to have a new default ilm policy created used by the beat.

**Playbook**:
```
---
- name: setup
  hosts: es-1
  tasks:
  - name: setup metricbeat kibana dashboards and templates
    include_role:
      name: elastic.beats
    vars:
      beats_version: 7.11.1
      beat: metricbeat
      version_lock: true
      default_ilm_policy: "../files/conf/new_policy.json"
      become: yes
      output_conf:
        elasticsearch:
          hosts: ["https://es-1:9200"]
          username: "redacted"
          password: "redacted"
          ssl.certificate: "/etc/ssl/localcerts/redacted.crt"
          ssl.key: "/etc/ssl/localcerts/redacted.key"
          ssl.certificate_authorities: ["/usr/local/share/ca-certificates/redacted.crt"]
          ssl.verification_mode: certificate
          index: "metricbeat"
      beat_conf:
        monitoring.enabled: true
        setup.kibana:
          host: "https://kbn-1:5601"
          username: "redacted"
          password: "redacted"
          ssl.certificate: "/etc/ssl/localcerts/redacted.crt"
          ssl.key: "/etc/ssl/localcerts/redacted.key"
          ssl.certificate_authorities: ["/usr/local/share/ca-certificates/redacted.crt"]
          ssl.verification_mode: certificate
        setup.dashboards.enabled: true
        setup.dashboards.index: "metricbeat-*"
        setup.ilm:
          enabled: true
          rollover_alias: "metricbeat"
          pattern: "000001"
          policy_file: "/etc/metricbeat/policies/new_policy.json
          overwrite: true
        setup.template:
          name: "metricbeat_template"
          overwrite: true
          pattern: "metricbeat-*"
          settings:
            index.number_of_shards: 1
            index.number_of_replicas: 0
        metricbeat.modules:
        - module: system
          metricsets:
            - cpu             # CPU usage
            - load            # CPU load averages
            - memory          # Memory usage
            - network         # Network IO
            - process         # Per process metrics
            - process_summary # Process summary
            - uptime          # System Uptime
            - socket_summary  # Socket summary
            #- core           # Per CPU core usage
            - diskio         # Disk IO
            #- filesystem     # File system usage for each mountpoint
            - fsstat         # File system summary metrics
            #- raid           # Raid
            - socket         # Sockets and connection info (linux only)
            - service        # systemd service information
          enabled: true
          period: 10s
          processes: ['.*']
        # Configure the metric types that are included by these metricsets.
          cpu.metrics:  ["percentages","normalized_percentages"]  # The other available option is ticks.
          core.metrics: ["percentages"]  # The other available option is ticks.
        - module: linux
          period: 10s
          metricsets:
            - "pageinfo"
            - "memory"
            # - ksm
            # - conntrack
            # - iostat
          enabled: true
          # hostfs: /hostfs
```

**Provide logs from Ansible**:
```
fatal: [es-1]: FAILED! => {"changed": false, "msg": "beat_conf.setup.ilm.policy_file must be specified if default_ilm_policy is used"}
```
I also spent some time using the Ansible debugger. I managed to see that indeed the variable was existing when I displayed `p task_vars['beatf_conf']` but when I added nested path `setup.ilm` I had the following error: `***KeyError:KeyError('beat_conf.setup.ilm')` so I don't really understand if it's a limitation of the debugger or if the issue is around those nested json paths or something else.

Thanks in advance for your help!
