### ISSUE TITLE
apt-mark unhold fails

### ISSUE THREAD

**Issue by aodren** [elastic/ansible-beats#145]
**Beats product**: any

**Beats version**: any

**Role version**:  v7.10.2

**OS version** : Linux srv01 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:

when installing from custom_package_url, unhold command fail with rc=100 if beat is not installed

**Playbook**:
```
beats_use_repository: false
beats_add_repository: false
metricbeat_package_url: 'file:///tmp/metricbeat-7.10.2-amd64.deb'
beat_output_conf:
  elasticsearch:
    enabled: true
    hosts:
      - els01
      - els02
    loadbalance: true
beat_conf_metricbeat:
  metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - diskio
      - service
    period: 10s
```

```
- hosts: all
  roles:
    - role: elastic_beats
      vars:
        beat: metricbeat
        beat_conf: "{{ beat_conf_metricbeat }}"
        output_conf: "{{ beat_output_conf }}"
        use_repository: "{{ beats_use_repository }}"
        custom_package_url: "{{ metricbeat_package_url | default('') }}"
```

**Provide logs from Ansible**:
```
TASK [elastic_beats : Debian - unhold metricbeat version for install] ***************************************************************************************************************************************
fatal: [srv01]: FAILED! => changed=false 
  cmd:
  - apt-mark
  - unhold
  - metricbeat
  delta: '0:00:00.123186'
  end: '2021-05-19 15:00:20.453167'
  msg: non-zero return code
  rc: 100
  start: '2021-05-19 15:00:20.329981'
  stderr: |-
    E: Unable to locate package metricbeat
    E: No packages found
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Beats logs if relevant**:
