### ISSUE TITLE
Support for Auditbeat and Winlogbeat

### ISSUE THREAD

**Issue by sherry-ger** [elastic/ansible-beats#36]
Please add support for Auditbeat and Winlogbeat.

**Comment by jmlrt** [comment]
Hi @sherry-ger,
Currently ansible-beats role is does only support Linux systems.

- Also Auditbeat hasn't been tested yet, it should work on Linux system with a playbook like that:

```yaml
---
- hosts: localhost
  roles:
    - role: "beats"
      vars:
        beat: "auditbeat"
        beat_conf:
          auditbeat.modules:
            - module: "file_integrity"
            - paths:
                - "/bin"
                - "/usr/bin"
                - "/sbin"
                - "/usr/sbin"
                - "/etc"
```

- As for Winlogbeat, the main requirement is to support Windows systems. We already have request to add Windows support (https://github.com/elastic/ansible-beats/issues/27 and https://github.com/elastic/ansible-beats/pull/17). The main issue is to adapt our test environment for Windows as our integration tests are currently done with Linux Docker containers.
