### ISSUE TITLE
output_conf is appended to default, not overwritten

### ISSUE THREAD

**Issue by marnikvde** [elastic/ansible-beats#45]
**Role version**:  https://github.com/elastic/ansible-beats/releases/tag/7.0.0

I'm not 100 sure since I'm no ansible expert, by my playbook uses these variables:

```yaml
beat: filebeat
beats_version: 7.3.2
beat_conf:
  inputs:
    - type: log
      enabled: true
      paths:
        - /foo/bar/*.log
      include_lines: ['sometext']
  path.logs: /var/log/filebeat
output_conf:
  logstash:
    hosts:
      - "somehost:9004"
```

And the resulting filebeat.yml that gets deployed reads:

```yaml
################### filebeat Configuration #########################

############################# filebeat ######################################
inputs:
-   enabled: true
    include_lines:
    - 'sometext'
    paths:
    - /foo/bar/*.log
    type: log
path.logs: /var/log/filebeat


###############################################################################
############################# Libbeat Config ##################################
# Base config file used by all other beats for using libbeat features

############################# Output ##########################################

output:
    elasticsearch:
        hosts:
        - localhost:9200
    logstash:
        hosts:
        - somehost:9004


############################# Logging #########################################

logging:
    files:
        rotateeverybytes: 10485760
```

This makes filebeat unable to start, since 2 different output options are not supported. I seems like my customer logstash output is _added_ to the default elasticsearch output on localhost, while it should be overwritten. If I understand it correctly, "elasticsearch" and "logstash" are different keys in the "output" dictionary, and hence they are co-existing. Probably easy to fix by removing the default, but I'm not sure what the proper fix would be.

Or am I missing something?

**Comment by jmlrt** [comment]
Hi @marnikvde,
I couldn't reproduce it locally, when running test with the same ansible role version and same variables (minus replacing `inputs` by `filebeat.inputs` in `beat_conf`) as yours, I get only the logstash output, not the elasticsearch output.
Are you sure that you aren't overriding `output_conf` or `beat_output_conf` somewhere else?

Also for your  `inputs` config is wrong. You should use `filebeats.inputs` instead of `inputs` in `beat_conf`as mentionned in [Configure inputs](https://www.elastic.co/guide/en/beats/filebeat/7.4/configuration-filebeat-options.html).

**Comment by AlphaRaven** [comment]
Got the same problem here:

```
- name: Install XXX Filebeat
  hosts: XXX-XX-XXX
  roles:
    - role: elastic.beats
      beat: filebeat
      beat_conf:
        filebeat:
          modules:
            - module: "panw"
              panos:
                enabled: true
                var.syslog_host: "0.0.0.0"
                var.syslog_port: 5514
        tags: ["filebeat", "XXX"]
      output_conf:
        redis:
          hosts:
            - "localhost:6379"
          password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              37643635386437643561646133303462336232353938666636353136663861333337616461383662
              61... XXXXXXXXX
          key: "XXX-filebeat"
```
and the result is:

```
# Ansible managed

################### filebeat Configuration #########################

############################# filebeat ######################################
filebeat:
  modules:
  - module: panw
    panos:
      enabled: true
      var.syslog_host: 0.0.0.0
      var.syslog_port: 5514
tags:
- filebeat
- XXX


###############################################################################
############################# Libbeat Config ##################################
# Base config file used by all other beats for using libbeat features

############################# Output ##########################################

output:
  elasticsearch:
    hosts:
    - localhost:9200
  redis:
    hosts:
    - localhost:6379
    key: XXX-filebeat
    password: XXXXXXX


############################# Logging #########################################

logging:
  files:
    rotateeverybytes: 10485760
```

Any advice here, please?

**Comment by jmlrt** [comment]
@AlphaRaven
I couldn't reproduce it. Running your playbook give me this `filebeat.yml`:
```yaml
# Ansible managed

################### filebeat Configuration #########################

############################# filebeat ######################################
filebeat:
  modules:
  - module: panw
    panos:
      enabled: true
      var.syslog_host: 0.0.0.0
      var.syslog_port: 5514
tags:
- filebeat
- XXX


###############################################################################
############################# Libbeat Config ##################################
# Base config file used by all other beats for using libbeat features

############################# Output ##########################################

output:
  redis:
    hosts:
    - localhost:6379
    key: XXX-filebeat
    password: XXXXXXX


############################# Logging #########################################

logging:
  files:
    rotateeverybytes: 10485760
```
