### ISSUE TITLE
'beat' host_var breaks restart handler

### ISSUE THREAD

**Issue by seanpringle** [elastic/ansible-beats#47]
**Beats product**:

filebeat

**Beats version**

7.0.0

**Role version**:  (If using master please specify github sha)

5ec7143a98caf935f91d0f53c8dc4904f4d4e520

**OS version** (`uname -a` if on a Unix-like system):

Ubuntu 18.04

**Description of the problem including expected versus actual behaviour**:

Defining the `beat` variable as a host_var breaks the restart handler on a fresh playbook run, with: `ERROR! 'beat' is undefined`. It isn't, though because role tasks referencing the variable succeed. Repeated attempts to run the playbook move the error to the next task that triggers a handler notification.

Think it might due to this limitation: https://github.com/ansible/ansible/issues/48466#issuecomment-437985126

Expected behaviour is that the beats role can use a host_var.

**Playbook**:
Please specify the full playbook used to reproduce this issue.

playbook:
```yaml
- hosts: appservers
  roles:
    - elastic.beats
```

host_vars:
```yaml
beat: filebeat
beat_conf:
  inputs:
    - type: log
      enabled: true
      paths:
        - /opt/app/log/*.log
```

**Provide logs from Ansible**:

```
...
TASK [beats : Debian - Ensure apt-transport-https is installed] **********************************************************************************************
ERROR! 'beat' is undefined
```

Repeated runs move the error to the next task that triggers a handler notify.
