### ISSUE TITLE
Support For Elastic Cloud

### ISSUE THREAD

**Issue by khawarhere** [elastic/ansible-beats#65]
**Feature request**

Provide support for [Elastic Cloud](https://cloud.elastic.co/), We could provide `cloud.id` and `cloud.auth` values ideally in `Playbook.yml`.

**Comment by jmlrt** [comment]
Hi @khawarhere,
You should already be able to use this ansible role with Elastic Cloud.
You can provide `cloud.id` and `cloud.auth` values in `beat_conf` Ansible variable.

**Comment by khawarhere** [comment]
Dear @jmlrt,

Thanks for the response, I got your point, Also it would be a great help, if you please describe some example, e.g in filebeat, how will we set `cloud.id` and `cloud.auth`
```      
- role: ansible-beats
      beat: filebeat
      beat_conf:
        filebeat:
          inputs:
            - paths:
                - /var/log/*.log
              type: log
```

Thank you.

**Comment by jmlrt** [comment]
`cloud.id` and `cloud.auth` can be set in `filebeat.yml` config file so you can use a playbook like that:

```
- hosts: localhost
  roles:
    - role: ansible-beats
      beat: filebeat
      beat_conf:
        filebeat:
          inputs:
            - paths:
                - /var/log/*.log
              type: log
        cloud.id: "XXX"
        cloud.auth: "elastic:XXX"
```
