### ISSUE TITLE
configuration per host

### ISSUE THREAD

**Issue by esseti** [elastic/ansible-beats#82]
Hi all,

do you have a tip on how I can create specifc moduels configuration for specific hosts?
lest see that i've metric beats,

I want to monitor for all the host thsi
      

>  - module: "system"
>             metricsets:
>               - cpu
>               - load
>               - filesystem
>               - fsstat
>               - memory
>               # - network
>               - process  
>             enabled: true
>             period: 10s
>             processes: [".*"]
>             cpu_ticks: false

But for the `postgres` machine i want to add also additional modules, what can I do? how can I do that with this role?
Should I create various play with differnt confs?

**Comment by VerosK** [comment]
TIMTOWDY: You can use Ansible `group_vars` and/or `host_vars` to specify the metricsets.

First specify global (shared) metricset in one variable at the global level for all hosts and then add additional metricset at the specific group level.

Global metrics (in `group_vars/all/es_beat.yml`)
```yaml
beat_config:
  - module: "system"
    metricsets: "{{ beat_metricsets_common + beat_metricsets_extra }}"

beat_metricsets_common: 
  - cpu
  - load

beat_metricsets_extra: []
```

Postgres specific ones (`group_vars/postgres/es_beat.yml`):
```yaml
beat_metricsets_extra: 
  - postgres
```
